### ISSUE TITLE
Error when using the 'range' parameter for Routes Advanced and Time Filter Advanced

### ISSUE THREAD

**Issue by Chris-Hutch-iGeo** [igeolise/traveltime-platform-qgis-plugin#15]
When entering a range value (either as a 'Departure / Search range width' or 'Arrival / Search range width') for the Time Map Advanced tool or Time Filter Advanced tool, an error is being returned:

Recieved error from the API.
Error code : 2
Description : Invalid request json
See : http://docs.traveltimeplatform.com/reference/error-codes
Addtionnal info :
obj.departure_searches[0].range.max_results: ['Path missing']
obj.departure_searches[1].range.max_results: ['Path missing']
See log for more details.
Traceback (most recent call last):
File "/Users/chrishutchinson/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/travel_time_platform_plugin/algorithms/base.py", line 87, in processAlgorithm
return self.doProcessAlgorithm(parameters, context, feedback)
File "/Users/chrishutchinson/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/travel_time_platform_plugin/algorithms/advanced.py", line 850, in doProcessAlgorithm
parameters, context, feedback, data=data
File "/Users/chrishutchinson/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/travel_time_platform_plugin/algorithms/base.py", line 224, in processAlgorithmMakeRequest
) from None
_core.QgsProcessingException: Got error 422 from API

**Comment by olivierdalang** [comment]
A. Don't you mean Route instead of TimeMap ? (I was able to reproduce the issue for TimeFilter and Route, but not TimeMap).

B. Also, the API doesn't seem to take into account the `max_results` settings for the TimeFilter endpoint, as I get exactly the same output whether I set 1 or 5. Not really sure it matters for the plugin though, as I guess it's only really useful if you're trying to get multiple routes alternatives, and the plugin doesn't really allow to output routes from the timefilter algorithm yet.

@Chris-Hutch-iGeo Please reopen if A. or B. is not OK.

**Comment by Chris-Hutch-iGeo** [comment]
All looks good thanks!
