### ISSUE TITLE
Plugin Fails to Install

### ISSUE THREAD

**Issue by gsdali** [igeolise/traveltime-platform-qgis-plugin#4]
I've just tried to install the TravelTime Plugin for QGIS  (MacOSX 10.14.5) and I have had the following errors thrown up:

`Couldn't load plugin 'travel_time_platform_plugin' due to an error when calling its classFactory() method `

`ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets' `
`
Traceback (most recent call last):
  File "/Applications/MacPorts/Qgis3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/elb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/travel_time_platform_plugin/__init__.py", line 2, in classFactory
    from .main import Main
  File "/Applications/MacPorts/Qgis3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/elb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/travel_time_platform_plugin/main.py", line 31, in 
    from .provider import Provider
  File "/Applications/MacPorts/Qgis3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/elb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/travel_time_platform_plugin/provider.py", line 3, in 
    from . import algorithms
  File "/Applications/MacPorts/Qgis3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/elb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/travel_time_platform_plugin/algorithms/__init__.py", line 1, in 
    from . import advanced, base, simple, utilities
  File "/Applications/MacPorts/Qgis3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/elb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/travel_time_platform_plugin/algorithms/simple.py", line 17, in 
    from .. import parameters
  File "/Applications/MacPorts/Qgis3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/elb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/travel_time_platform_plugin/parameters.py", line 2, in 
    from .ui import IsoDateTimeWidgetWrapper
  File "/Applications/MacPorts/Qgis3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/elb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/travel_time_platform_plugin/ui.py", line 5, in 
    from qgis.PyQt.QtWebKitWidgets import QWebView
  File "/Applications/MacPorts/Qgis3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/MacPorts/Qgis3.app/Contents/MacOS/../Resources/python/qgis/PyQt/QtWebKitWidgets.py", line 26, in 
    from PyQt5.QtWebKitWidgets import *
  File "/Applications/MacPorts/Qgis3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets' `

Looking at my setup I have ` qt5-qtwebkit @5.9.1_3 ` installed. From what I can glean from the web `QtWebKitWidgets` has been deprecated and been replaced with`QtWebEngineWidgets`. Any help getting this working would be much appreciated.

**Comment by olivierdalang** [comment]
Thanks for the detailed report. It seems there's no reliable way to display a browser in pyqgis currently (QtWebEngineWidgets doesn't work either : https://github.com/qgis/QGIS/issues/26048)

Since this is just for online help, I'll add a check and directly open the help in the browser if not available.

Expect a fix later today.

**Comment by olivierdalang** [comment]
@gsdali Can you test again ? (it may take some time until 1.0.1 is available in the plugin manager)

**Comment by gsdali** [comment]
I will do as soon as I get home. (In Australia and heading to dinner)

**Comment by gsdali** [comment]
Sorry for the delay. That installed fine and the behaviour was as expected when clicking on help -> It launches the browser and comes to the help page on GitHub.

Thanks for the quick fix.
